Probando..

diff --git a/.github/workflows/helloWorld.yaml b/.github/workflows/helloWorld.yaml
--- a/.github/workflows/helloWorld.yaml
+++ b/.github/workflows/helloWorld.yaml
@@ -10,22 +10,26 @@ jobs: ##3
     runs-on: ubuntu-20.04
     steps:
       - uses: actions/checkout@v4
-      - name: Failing step
-        id: demo
-        run: exit 1
-      - name: Test Success
-        uses: rjstone/discord-webhook-notify@v1.0.4 
-        if: success()
-        with:
-            severity: info
-            details: Test Succeeded!
-            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
-      - name: Test Failure
-        uses: rjstone/discord-webhook-notify@v1.0.4 
-        if: failure()
-        with: 
-            severity: error
-            details: Test Failed!
-            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
+      name: Extract commit hash
+      run: |
+        COMMIT_HASH=${{ github.sha }}
+        echo "Commit hash: $COMMIT_HASH"
+      # - name: Failing step
+      #   id: demo
+      #   run: exit 1
+      # - name: Test Success
+      #   uses: rjstone/discord-webhook-notify@v1.0.4 
+      #   if: success()
+      #   with:
+      #       severity: info
+      #       details: Test Succeeded!
+      #       webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
+      # - name: Test Failure
+      #   uses: rjstone/discord-webhook-notify@v1.0.4 
+      #   if: failure()
+      #   with: 
+      #       severity: error
+      #       details: Test Failed!
+      #       webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
 
         
